POST http://localhost:3001/api/games/62780db26dab7bbd13a2880c/moves HTTP/1.1
content-type: application/json

{
    "piece": {
        "pieceType": "pawn",
        "color": "white"
    },
    "from": [3, 3],
    "to": [3, 5] 
}
