POST http://localhost:3001/api/games/628124141df887e0ebdb0d1d/moves HTTP/1.1
content-type: application/json

{
    "piece": {
        "type": "knight",
        "color": "white"
    },
    "from": "g1",
    "to": "f3"
}
